name: "Env setup"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "yarn"
    - run: yarn install --ci
      shell: bash
    - name: Start site
      uses: tpluscode/action-setup-lando@v0.1.5
      with:
        version: v3.11.0
        healthcheck: https://cube-creator.lndo.site/ping
        timeout: 30000
      env:
        DOCKER_BUILDKIT: "1"
