name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Prepeare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: yarn

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_PRIVATE_KEY }}

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        with:
          commit: "chore: release"
          title: "Merge to release"

  tags:
    name: Create tags
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_PRIVATE_KEY }}

      - name: Tag Core API
        uses: ButlerLogic/action-autotag@1.1.2
        continue-on-error: true
        with:
          root: apis/core
          tag_prefix: cube-creator-api/v
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Tag UI
        uses: ButlerLogic/action-autotag@1.1.2
        continue-on-error: true
        with:
          root: ui
          tag_prefix: cube-creator-app/v
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Tag CLI
        uses: ButlerLogic/action-autotag@1.1.2
        continue-on-error: true
        with:
          root: cli
          tag_prefix: cube-creator-cli/v
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
